version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx2g"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk-net
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    image: logstash:8.15.0
    container_name: logstash01
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk-net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9600/_node/pipelines | grep -q 'pipeline'"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:8.15.0
    container_name: kibana01
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-net
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  filebeat:
    image: elastic/filebeat:8.15.0
    container_name: filebeat01
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/elk:/var/log/elk:ro
    depends_on:
      - logstash
    networks:
      - elk-net
    healthcheck:
      test: ["CMD", "filebeat", "test", "config", "-e"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticdump:
    build:    
      context: ./elasticdump
    container_name: elasticdump
    depends_on:
      - elasticsearch
      - minio
    volumes:
      - ./dumps:/dumps
      - ./elasticdump:/elasticdump
    networks:
      - elk-net
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f export-and-upload.sh >/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio01
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 'minio12345678@'
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - elk-net
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  es_data:
    driver: local

networks:
  elk-net:
    driver: bridge

