version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: es01
    environment:
      - discovery.type=single-node
      ################
      - xpack.security.enabled=false #was true
      - ELASTIC_PASSWORD=elastic12345678@ #existance
      ############
      - "ES_JAVA_OPTS=-Xms1g -Xmx2g"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk-net

  logstash:
    image: logstash:8.15.0
    container_name: logstash01
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

  kibana:
    image: kibana:8.15.0
    container_name: kibana01
    environment:
      ######################3333
      - ELASTICSEARCH_HOSTS=http://es01:9200 # was ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic12345678@
     ########################## 
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

  filebeat:
    image: elastic/filebeat:8.15.0
    container_name: filebeat01
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/elk:/var/log/elk:ro
    depends_on:
      - logstash
    networks:
      - elk-net

volumes:
  es_data:
    driver: local

networks:
  elk-net:
    driver: bridge
