version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - minio.env
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

volumes:
  minio-data:
